examples/vis_safety_gymnasium.py

Fix vis safety_gym_v2 with del the render_mode

fix(examples): del render_model

---

examples/vis_safety_gymnasium.py
omnisafe/envs/Safety_Gymnasium/examples/safety_gym_v2_vision.py
omnisafe/envs/Safety_Gymnasium/examples/vis_safety_gym_v2.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/__init__.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/base_task.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/builder.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/engine.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/tasks/button/button_level0.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/tasks/button/button_level1.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/tasks/goal/goal_level0.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/tasks/goal/goal_level1.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/tasks/push/push_level0.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/tasks/push/push_level1.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/world.py
omnisafe/envs/Safety_Gymnasium/tests/test_safety_gym_v2.py
omnisafe/envs/Safety_Gymnasium/tests/test_safety_gym_v2_vision.py

add render mode and vision input in Safety_Gymnasium/safety_gym_v2
This change solve the `close #4 `

add render mode and vision input in Safety_Gymnasium/safety_gym_v2

---

.pre-commit-config.yaml
examples/train_model_based.py
omnisafe/__init__.py
omnisafe/algo_wrapper.py
omnisafe/algos/__init__.py
omnisafe/algos/configs/model_based_cfgs/MBPPOLag.yaml
omnisafe/algos/configs/model_based_cfgs/SafeLoop.yaml
omnisafe/algos/model_based/arc.py
omnisafe/algos/model_based/aux.py
omnisafe/algos/model_based/env_wrappers.py
omnisafe/algos/model_based/mbppo.py
omnisafe/algos/model_based/models/core_ac.py
omnisafe/algos/model_based/models/core_sac.py
omnisafe/algos/model_based/models/dynamics_predict_env.py
omnisafe/algos/model_based/models/dynamicsmodel.py
omnisafe/algos/model_based/policy_gradient.py
omnisafe/algos/model_based/replay_memory.py
omnisafe/algos/model_based/safeloop.py
omnisafe/algos/utils/tools.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/builder.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/tasks/__init__.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/tasks/goal/goal_level3.py

add 2 modelbased algo:mbppo-lag and safeloop
add 2 modelbased algo:mbppo-lag and safeloop
- [] I have updated the tests accordingly. (*required for a bug fix or a new feature*)

add:model_based mbppolag,safeloop

---

README.md
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/builder.py
omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/engine.py

Support rgb_array, and Close #14 

feat(envs): support rgb_array and add metadata

---

CHANGELOG.md
docs/source/Documentation/Introduction.rst
docs/source/SafeRL/CPO.rst
docs/source/SafeRL/FOCOPS.rst
docs/source/SafeRL/PCPO.rst
docs/source/index.rst

Add docs for FOCOPS and PCPO
Closes #17 
Update documentation of FOCOPS and PCPO.

docs(focops,pcpo): add docs for FOCOPS and PCPO

---

CHANGELOG.md

refactor: update CHANGLOG.md

---

.pylintrc
envs/safety-gymnasium/safety_gymnasium/__init__.py
envs/safety-gymnasium/safety_gymnasium/agents/__init__.py
envs/safety-gymnasium/safety_gymnasium/agents/ant.py
envs/safety-gymnasium/safety_gymnasium/assets/geoms/sigwalls.py
envs/safety-gymnasium/safety_gymnasium/assets/xmls/ant.xml
envs/safety-gymnasium/tests/test_env.py
envs/safety-gymnasium/tests/test_vision_env.py

feat(agents): add ant agent

---

envs/safety-gymnasium/examples/env.py
envs/safety-gymnasium/safety_gymnasium/__init__.py
envs/safety-gymnasium/safety_gymnasium/bases/underlying.py
envs/safety-gymnasium/safety_gymnasium/utils/keyboard_viewer.py

1. Add keyboard debug mode for some agents in all tasks.

feat(render): add keyboard debug mode for some agents in all tasks

---

omnisafe/configs/off-policy/DDPG.yaml
omnisafe/configs/off-policy/DDPGLag.yaml
omnisafe/configs/off-policy/DDPGPid.yaml
omnisafe/configs/off-policy/DDPGSafetyLayer.yaml
omnisafe/configs/off-policy/OffCRPO.yaml
omnisafe/configs/off-policy/SAC.yaml
omnisafe/configs/off-policy/TD3.yaml
omnisafe/configs/off-policy/TD3Lag.yaml
omnisafe/configs/on-policy/CPO.yaml
omnisafe/configs/on-policy/CPPOPid.yaml
omnisafe/configs/on-policy/FOCOPS.yaml
omnisafe/configs/on-policy/NaturalPG.yaml
omnisafe/configs/on-policy/OnCRPO.yaml
omnisafe/configs/on-policy/PCPO.yaml
omnisafe/configs/on-policy/PPO.yaml
omnisafe/configs/on-policy/PPOEarlyTerminated.yaml
omnisafe/configs/on-policy/PPOLag.yaml
omnisafe/configs/on-policy/PPOLagEarlyTerminated.yaml
omnisafe/configs/on-policy/PPOLagSaute.yaml
omnisafe/configs/on-policy/PPOLagSimmerPid.yaml
omnisafe/configs/on-policy/PPOLagSimmerQ.yaml
omnisafe/configs/on-policy/PPOSaute.yaml
omnisafe/configs/on-policy/PPOSimmerPid.yaml
omnisafe/configs/on-policy/PPOSimmerQ.yaml
omnisafe/configs/on-policy/PolicyGradient.yaml
omnisafe/configs/on-policy/RCPO.yaml
omnisafe/configs/on-policy/TRPO.yaml
omnisafe/configs/on-policy/TRPOLag.yaml
omnisafe/configs/on-policy/TRPOPid.yaml

chore: update algorithms configration

---

.pre-commit-config.yaml
omnisafe/configs/on-policy/CPO.yaml
omnisafe/configs/on-policy/CPPOPid.yaml
omnisafe/configs/on-policy/CUP.yaml
omnisafe/configs/on-policy/FOCOPS.yaml
omnisafe/configs/on-policy/IPO.yaml
omnisafe/configs/on-policy/NaturalPG.yaml
omnisafe/configs/on-policy/P3O.yaml
omnisafe/configs/on-policy/PDO.yaml
omnisafe/configs/on-policy/PPO.yaml
omnisafe/configs/on-policy/PPOEarlyTerminated.yaml
omnisafe/configs/on-policy/PPOLag.yaml
omnisafe/configs/on-policy/PPOLagEarlyTerminated.yaml
omnisafe/configs/on-policy/PPOLagSaute.yaml
omnisafe/configs/on-policy/PPOLagSimmerPid.yaml
omnisafe/configs/on-policy/PPOLagSimmerQ.yaml
omnisafe/configs/on-policy/PPOSaute.yaml
omnisafe/configs/on-policy/PPOSimmerPid.yaml
omnisafe/configs/on-policy/PPOSimmerQ.yaml
omnisafe/configs/on-policy/PolicyGradient.yaml

chore: update yaml

---

omnisafe/algorithms/algo_wrapper.py
omnisafe/algorithms/off_policy/ddpg.py
omnisafe/algorithms/on_policy/base/policy_gradient.py

fix: fix algo wrapper

---

omnisafe/utils/tools.py

fix: fix tools

---

omnisafe/algorithms/off_policy/ddpg.py
omnisafe/algorithms/off_policy/sddpg.py
omnisafe/algorithms/on_policy/base/natural_pg.py
omnisafe/algorithms/on_policy/base/policy_gradient.py
omnisafe/algorithms/on_policy/base/trpo.py
omnisafe/algorithms/on_policy/second_order/cpo.py
omnisafe/algorithms/on_policy/second_order/pcpo.py

fix #110 
1. add assert message
The assert check of some codes lacks error message prompts. Adding these hints can give users a better understanding of the source of the bug.

fix: ensure the step of each epoch

---

omnisafe/common/buffer/onpolicy_buffer.py
omnisafe/common/buffer/vector_onpolicy_buffer.py
omnisafe/common/logger.py
omnisafe/wrappers/cmdp_wrapper.py
tests/test_buffer.py

fix buffer's bugs, which could cause train fails

fix(buffer): fix buffer bugs

---

omnisafe/configs/on-policy/PPO.yaml

chore: update yaml
The actor of PPO must be `gaussian` instead of `gaussian_stdnet`.

chore(ppo.yaml): update ppo.yaml

---

omnisafe/configs/on-policy/PPO.yaml
omnisafe/evaluator.py

fix(evaluator): fix evaluator
There is an indentation error in the evaluator

fix(evaluator): fix evaluator

---

omnisafe/adapter/online_adapter.py
omnisafe/algorithms/algo_wrapper.py
omnisafe/algorithms/base_algo.py
omnisafe/algorithms/on_policy/base/policy_gradient.py
omnisafe/configs/on-policy/PDO.yaml
omnisafe/configs/on-policy/PPO.yaml
omnisafe/envs/core.py
omnisafe/envs/wrapper.py
omnisafe/evaluator.py

1. fix algo_wrapper::learn can't return normailly
2. save obs_normailze
3. eval abstract class

fix(algo): fix no return in algo_wrapper::learn

---

omnisafe/algorithms/algo_wrapper.py
omnisafe/algorithms/base_algo.py
omnisafe/configs/on-policy/CPO.yaml
omnisafe/configs/on-policy/CPPOPid.yaml
omnisafe/configs/on-policy/CUP.yaml
omnisafe/configs/on-policy/FOCOPS.yaml
omnisafe/configs/on-policy/IPO.yaml
omnisafe/configs/on-policy/NaturalPG.yaml
omnisafe/configs/on-policy/OnCRPO.yaml
omnisafe/configs/on-policy/P3O.yaml
omnisafe/configs/on-policy/PCPO.yaml
omnisafe/configs/on-policy/PDO.yaml
omnisafe/configs/on-policy/PPO.yaml
omnisafe/configs/on-policy/PPOEarlyTerminated.yaml
omnisafe/configs/on-policy/PPOLag.yaml
omnisafe/configs/on-policy/PPOLagEarlyTerminated.yaml
omnisafe/configs/on-policy/PPOLagSaute.yaml
omnisafe/configs/on-policy/PPOLagSimmerPid.yaml
omnisafe/configs/on-policy/PPOLagSimmerQ.yaml
omnisafe/configs/on-policy/PPOSaute.yaml
omnisafe/configs/on-policy/PPOSimmerPid.yaml
omnisafe/configs/on-policy/PPOSimmerQ.yaml
omnisafe/configs/on-policy/PolicyGradient.yaml
omnisafe/configs/on-policy/RCPO.yaml
omnisafe/configs/on-policy/TRPO.yaml
omnisafe/configs/on-policy/TRPOLag.yaml
omnisafe/configs/on-policy/TRPOPid.yaml

chore: support num_thread setting

---

omnisafe/algorithms/on_policy/penalty_function/p3o.py
omnisafe/configs/on-policy/P3O.yaml

In issues #118 we found something wrong with p3o. This PR fix this bug.
`close #118`

fix(P3O): fix P3O performance

---

omnisafe/algorithms/off_policy/crpo.py
omnisafe/algorithms/off_policy/ddpg.py
omnisafe/algorithms/off_policy/ddpg_lag.py
omnisafe/algorithms/off_policy/ddpg_pid.py
omnisafe/algorithms/off_policy/sac.py
omnisafe/algorithms/off_policy/sac_lag.py
omnisafe/algorithms/off_policy/sac_pid.py
omnisafe/algorithms/off_policy/sddpg.py
omnisafe/algorithms/off_policy/td3.py
omnisafe/algorithms/off_policy/td3_lag.py
omnisafe/algorithms/off_policy/td3_pid.py
omnisafe/configs/off-policy/DDPG.yaml
omnisafe/configs/off-policy/DDPGLag.yaml
omnisafe/configs/off-policy/DDPGPid.yaml
omnisafe/configs/off-policy/SAC.yaml
omnisafe/configs/off-policy/SACLag.yaml
omnisafe/configs/off-policy/TD3.yaml
omnisafe/configs/off-policy/TD3Lag.yaml
omnisafe/configs/off-policy/TD3Pid.yaml
omnisafe/wrappers/cmdp_wrapper.py

fix(off-policy): fix actions passing bug
Solve issue #120 

fix(off-policy): fix action passing

---

README.md
omnisafe/algorithms/on_policy/base/ppo.py

PPO should maximize entropy when updating the policy, while currently PPO on the main branch minimizes entropy. We discovered this problem and made corrections in time. Since the default value of ``entropy_coef`` in the ``ppo.yaml`` file is 0, it does not affect the experimental performance of the previous PPO. We are sorry for this and have given a timely revision.

fix(ppo): fix entropy loss

---

README.md
examples/train_from_custom_dict.py
examples/train_from_yaml.py

docs: update README.md

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/test.yml
omnisafe/algorithms/algo_wrapper.py
omnisafe/common/logger.py
tests/test_policy.py

Support different version of test in workflow

chore: update github workflow

---

CHANGELOG.md

docs: update changelog.md

---

omnisafe/common/experiment_grid.py

1. Check duplicated parameters and values which are specified in experiment grid

fix: check duplicated parameters and values which are specified in experiment grid

---

benchmarks/README.md
omnisafe/configs/on-policy/CUP.yaml
omnisafe/configs/on-policy/FOCOPS.yaml
omnisafe/configs/on-policy/P3O.yaml
omnisafe/configs/on-policy/PPO.yaml
omnisafe/configs/on-policy/PPOLag.yaml
omnisafe/configs/on-policy/PolicyGradient.yaml

1. Update hyper-parameters for first-order algorithms.

refactor: update hyper-parameters for first-order algorithms

---

omnisafe/common/statistics_tools.py
omnisafe/utils/plotter.py

1.  Enable `smooth` param in `Costs` when plotting.
- [] I have updated the documentation accordingly.

fix: enable `smooth` param in `Costs` when plotting

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

It's a small change that probably doesn't affect anything, but hey, doesn't hurt to get the spelling checked, right?
;)

docs: fix small typo in README.md

---

README.md
conda-recipe.yaml
pyproject.toml
tutorials/English/1.Getting_Started.ipynb
tutorials/English/2.CLI_Command.ipynb
tutorials/requirements.txt
tutorials/zh-cn/1.Getting Started.ipynb
tutorials/zh-cn/2.CLI Command.ipynb

1. bump the PyTorch upper bound version to 2.0
2. remove the anaconda virtual environment in tutorial
link to BUG Issue: #218 

refactor: minor changes regarding documentation and dependencies

---

.github/PULL_REQUEST_TEMPLATE.md
CODEOWNERS

solve the feature request #232 
feature request #232 

feat: add `CODEOWNERS` and refine `ISSUE TEMPLATE`

---

CHANGELOG.md
README.md
benchmarks/model-based/README.md
benchmarks/off-policy/README.md
benchmarks/offline/README.md
benchmarks/on-policy/README.md
examples/collect_offline_data.py
omnisafe/configs/off-policy/DDPG.yaml
omnisafe/configs/off-policy/DDPGLag.yaml
omnisafe/configs/off-policy/SAC.yaml
omnisafe/configs/off-policy/SACLag.yaml
omnisafe/configs/off-policy/TD3.yaml
omnisafe/configs/off-policy/TD3Lag.yaml

Image title of off-policy benchmarks is wrong. This PR fix it.

docs: polish README, benchmarks and examples

---

docs/source/baserl/trpo.rst

fix a little formula error in TRPO.

docs: fix formula error in TRPO

---

.pre-commit-config.yaml
omnisafe/algorithms/model_based/base/loop.py
omnisafe/algorithms/model_based/base/pets.py
omnisafe/algorithms/on_policy/second_order/pcpo.py
omnisafe/utils/tools.py

- Update code style to meet the new requirement of ``ruff``.
- Update ``pre-commit.yaml`` as well
``ruff`` failed in PR #260, this PR fix it.

style: update pre-commit.yaml and fix ruff

---

omnisafe/envs/mujoco_env.py

Enable AutoReset wrapper for Mujoco envs. 
Closes #268

fix(envs): Enable auto reset for MuJoCo envs

---

tutorials/README.md

fix: fix invalid tutorial links

---

benchmarks/offline/README.md
examples/collect_offline_data.py

Fix the misalignment between the code and the example docs of the offline data collector. 
We missed ``.pt`` in the tutorial, and this PR fixed it.
More details can refer to discussion [here](https://github.com/PKU-Alignment/omnisafe/discussions/288).

docs: fix offline data collection docs

---

.github/workflows/lint.yml
.pylintrc
docs/source/benchmark/case-study.md
docs/source/benchmark/modelbased.md
docs/source/benchmark/off-policy.md
docs/source/benchmark/offline.md
docs/source/benchmark/on-policy.md
docs/source/index.rst
docs/source/spelling_wordlist.txt
docs/source/start/algo.md
docs/source/start/efficiency.rst
docs/source/start/exp-grid.md
docs/source/start/features.md
omnisafe/adapter/modelbased_adapter.py
omnisafe/common/logger.py
omnisafe/common/offline/data_collector.py
omnisafe/envs/classic_control/envs_from_crabs.py
omnisafe/envs/safety_gymnasium_modelbased.py
omnisafe/evaluator.py
omnisafe/utils/plotter.py
pyproject.toml

Move the appendix from our paper to website docs.

docs: update appendix
