envs/safety-gymnasium/examples/safety_gym_v2_vision.py, envs/safety-gymnasium/tests/test_safety_gym_v2.py, omnisafe/algos/env_wrapper.py
…init__().
Fix warning caused by 'none' string default value in parameters of __init__().
It looks like:
It solves a wrong warning.
=> fix(env_wrapper): fix warning caused by 'none' string default value in parameters of __init__().

docs/source/SafeRL/Lag.rst, omnisafe/algorithms/model_based/cap.py, omnisafe/algorithms/model_based/planner.py, omnisafe/algorithms/model_based/policy_gradient.py, omnisafe/common/lagrange.py, omnisafe/configs/model-based/CAP.yaml, omnisafe/wrappers/model_based_wrapper.py
fix cap cost bug and lag beta value in cap.yaml, epcosts to epcost
=> fix(model-based): fix cap cost bug and lag beta value in cap.yaml

omnisafe/algorithms/on_policy/base/policy_gradient.py, omnisafe/common/logger.py, omnisafe/configs/on-policy/CPO.yaml, omnisafe/envs/wrapper.py, omnisafe/utils/math.py
fix(logger, wrapper): support csv file and velocity tasks
- [ x I have read the [CONTRIBUTION](https://omnisafe.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
=> fix(logger, wrapper): support csv file and velocity tasks

omnisafe/algorithms/on_policy/base/natural_pg.py, omnisafe/algorithms/on_policy/base/policy_gradient.py, omnisafe/algorithms/on_policy/base/ppo.py, omnisafe/algorithms/on_policy/base/trpo.py, omnisafe/algorithms/on_policy/first_order/cup.py, omnisafe/algorithms/on_policy/first_order/focops.py, omnisafe/algorithms/on_policy/penalty_function/p3o.py, omnisafe/algorithms/on_policy/second_order/cpo.py, omnisafe/algorithms/on_policy/second_order/pcpo.py
=> chore: fix typo.

examples/evaluate_saved_policy.py, omnisafe/__init__.py, omnisafe/adapter/online_adapter.py, omnisafe/common/normalizer.py, omnisafe/envs/wrapper.py, omnisafe/evaluator.py
feat: support policy evaluation
=> feat: support policy evaluation

omnisafe/adapter/onpolicy_adapter.py, omnisafe/algorithms/algo_wrapper.py, omnisafe/common/experiment_grid.py
1. Explicitly distinguish the terminated and truncated.
2. Fix the parent path named by the config in exp_grid.
=> fix(rollout, exp_grid): fix logdir path conflict

examples/train_policy.py, omnisafe/adapter/offpolicy_adapter.py, omnisafe/adapter/online_adapter.py, omnisafe/adapter/saute_adapter.py, omnisafe/algorithms/on_policy/second_order/cpo.py, omnisafe/algorithms/on_policy/second_order/pcpo.py, omnisafe/envs/core.py, omnisafe/envs/safety_gymnasium_env.py, omnisafe/envs/wrapper.py, omnisafe/evaluator.py
=> refactor(wrapper): refactor the cuda setting

MANIFEST.in, omnisafe/version.py, pyproject.toml, setup.py
=> chore: add MANIFEST.in

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/questions.yml, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CONTRIBUTING.md, README.md, benchmarks/README.md, docs/source/conf.py, docs/source/index.rst, docs/source/start/installation.rst, docs/source/start/usage.rst, pyproject.toml, setup.py, tutorials/README.md
Because of migrating the repo from the organization `PKU-MARL` to `OmniSafeAI`, we need to update the links in it.
=> docs: change link to OmniSafeAI

omnisafe/adapter/offpolicy_adapter.py, omnisafe/adapter/onpolicy_adapter.py, omnisafe/adapter/saute_adapter.py, omnisafe/algorithms/off_policy/ddpg.py, omnisafe/algorithms/off_policy/ddpg_lag.py, omnisafe/algorithms/off_policy/sac.py, omnisafe/algorithms/off_policy/sac_lag.py, omnisafe/algorithms/off_policy/td3.py, omnisafe/algorithms/off_policy/td3_lag.py, omnisafe/algorithms/on_policy/base/natural_pg.py, omnisafe/algorithms/on_policy/base/policy_gradient.py, omnisafe/algorithms/on_policy/base/trpo.py, omnisafe/algorithms/on_policy/first_order/cup.py, omnisafe/algorithms/on_policy/first_order/focops.py, omnisafe/algorithms/on_policy/naive_lagrange/pdo.py, omnisafe/algorithms/on_policy/naive_lagrange/ppo_lag.py, omnisafe/algorithms/on_policy/naive_lagrange/rcpo.py, omnisafe/algorithms/on_policy/naive_lagrange/trpo_lag.py, omnisafe/algorithms/on_policy/penalty_function/ipo.py, omnisafe/algorithms/on_policy/penalty_function/p3o.py, omnisafe/algorithms/on_policy/pid_lagrange/cppo_pid.py, omnisafe/algorithms/on_policy/pid_lagrange/trpo_pid.py, omnisafe/algorithms/on_policy/second_order/cpo.py, omnisafe/algorithms/on_policy/second_order/pcpo.py, omnisafe/common/logger.py
Refactor and simplify logger storage logic.
=> refactor(common/logger): refactor and simplify logger storage logic

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/questions.yml, .github/PULL_REQUEST_TEMPLATE.md, CODEOWNERS, CONTRIBUTING.md, README.md, docs/source/conf.py, docs/source/start/usage.rst, omnisafe/common/logger.py, pyproject.toml, tutorials/English/1.Getting_Started.ipynb, tutorials/English/2.CLI_Command.ipynb, tutorials/README.md, tutorials/zh-cn/1.Getting Started.ipynb, tutorials/zh-cn/2.CLI Command.ipynb
Change link to PKU-Alignment
Since the name of organization has been changed to PKU-Alignment, all links related need to be redirected.
=> docs: change link to PKU-Alignment

omnisafe/adapter/early_terminated_adapter.py, omnisafe/adapter/saute_adapter.py, omnisafe/adapter/simmer_adapter.py, omnisafe/common/experiment_grid.py, omnisafe/common/statistics_tools.py, omnisafe/models/actor/perturbation_actor.py, omnisafe/models/actor/vae_actor.py, omnisafe/models/critic/q_critic.py, omnisafe/models/offline/dice.py
- fix cuda support of `saute`, `simmer` and `early mdp`.
- fix stastistics tools
- fix experiment grid
=> fix: fix adapter device and exp grid

.pre-commit-config.yaml, omnisafe/common/offline/dataset.py, omnisafe/envs/core.py, omnisafe/envs/mujoco_env.py, omnisafe/envs/safety_gymnasium_env.py, omnisafe/envs/safety_gymnasium_modelbased.py, omnisafe/utils/math.py, tests/simple_env.py
Fix code style according to the newest `ruff`.
Due to the `ruff` version update, the current code does not comply with the latest `ruff` specifications. PR #250 has encountered issues during the `lint` check. This pull request will modify the code according to the latest Ruff specifications, enabling PR #250 to merge after rebasing.
=> style: fix ruff check

omnisafe/common/pid_lagrange.py
=> fix: correct the author list of PIDLag

omnisafe/algorithms/algo_wrapper.py, omnisafe/algorithms/off_policy/ddpg.py, omnisafe/algorithms/off_policy/sac.py, omnisafe/algorithms/off_policy/td3.py
Remove redundant distributed average gradient in off-policy algorithms
Resolve issue #252 
=> chore(off-policy): clear redundant distributed grad average

omnisafe/algorithms/on_policy/primal/crpo.py, omnisafe/configs/on-policy/OnCRPO.yaml
The original implementation of CRPO uses TRPO as the base algorithm.
We rebase the on-policy version of CRPO, that is, `OnCRPO`, from PPO to TRPO, and tune the config file.
We evaluate the new implementation in the following environment in [SafetyGymnasium](https://github.com/PKU-Alignment/safety-gymnasium):
**SafetyCarGoal1-v0**
**SafetyPointGoal1-v0**
**SafetyAntVelocity-v1**
**SafetyHalfCheetahVelocity-v1**
**SafetyHopperVelocity-v1**
**SafetyHumanoidVelocity-v1**
**SafetyWalker2dVelocity-v1**
**SafetySwimmerVelocity-v1**
The performance of CRPO can not reach our expectation and it is different from original implementation.
Go over all the following points, and put an `x` in all the boxes that …
=> feat: rebase CRPO from PPO to TRPO

omnisafe/adapter/offpolicy_adapter.py, omnisafe/adapter/online_adapter.py, omnisafe/algorithms/off_policy/ddpg.py, omnisafe/configs/off-policy/DDPG.yaml, omnisafe/configs/off-policy/DDPGLag.yaml, omnisafe/configs/off-policy/DDPGPID.yaml, omnisafe/configs/off-policy/SAC.yaml, omnisafe/configs/off-policy/SACLag.yaml, omnisafe/configs/off-policy/SACPID.yaml, omnisafe/configs/off-policy/TD3.yaml, omnisafe/configs/off-policy/TD3Lag.yaml, omnisafe/configs/off-policy/TD3PID.yaml
- [feat: support evaluation episodes configuration](https://github.com/PKU-Alignment/omnisafe/commit/a90dbfd164ffc7c6285a6506c84924f5d65a83e4)
- [fix: fix final observation setting in off-policy algorithms](https://github.com/PKU-Alignment/omnisafe/commit/30d90f86f6a8b666ea5757740dbfab14e92488e1)
- Previously the off-policy algorithms must evaluate once per episode, This pull request would set the times of evaluation as a configuration. If you do not want to evaluate during training process, please set it to 0.
- We process the ``final_observation`` to address the issue of the end of trajectory. However, not all environments have the key ``final_observation`` in the ``info`` of ``step`` function. So we fix it by a simple ``if-else`` judgement.
What types of changes does your code …
=> feat(off-policy): fix final_obsevation setting and support evaluation times configuation

.pre-commit-config.yaml, omnisafe/adapter/offline_adapter.py, omnisafe/adapter/online_adapter.py, omnisafe/adapter/saute_adapter.py, omnisafe/adapter/simmer_adapter.py, omnisafe/algorithms/model_based/planner/arc.py, omnisafe/algorithms/model_based/planner/cem.py, omnisafe/algorithms/model_based/planner/safe_arc.py, omnisafe/common/logger.py, omnisafe/envs/core.py, omnisafe/envs/mujoco_env.py, omnisafe/envs/safety_gymnasium_env.py, omnisafe/envs/safety_gymnasium_modelbased.py, omnisafe/envs/wrapper.py, omnisafe/utils/distributed.py, omnisafe/utils/model.py, omnisafe/utils/schedule.py, tests/simple_env.py
The ``reset`` functions in wrapper, env and adapter are not suitable for [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) style API, which miss an ``option`` argument. This pull request add this interface and would not affect the previous usage and performance.
It solves issue #265 
=> feat: support gymnasium style reset API

docs/requirements.txt
Pin the version of ``sphinx`` as 7.1.2.
Some issue exists in the 7.2.3 version of ``sphinx``.
Read the docs would fail building the online documentation.
The error information is:
```python
File "/home/docs/checkouts/readthedocs.org/user_builds/omnisafe/envs/latest/lib/python3.9/site-packages/torch/__init__.py", line 1157, in <module>
from torch._C._VariableFunctions import *  # type: ignore[misc] # noqa: F403
ModuleNotFoundError: No module named 'torch._C._VariableFunctions'; 'torch._C' is not a package
```
So this pull request pin the version of ``sphinx`` in 7.1.2 to solve it.
If you are unsure about any of these, don't …
=> docs: pin dependency

pyproject.toml
Pin the version of pandas as 2.0.3.
Since the [seaborn](https://github.com/mwaskom/seaborn) host in pypi do not support the latest version of [pandas](), some warning may arise in Python version higher than 3.9, like:
```bash
FAILED test_policy.py::test_workflow_for_training[algo(PPO)] - FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
FAILED test_policy.py::test_workflow_for_training[algo(SAC)] - FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
FAILED test_policy.py::test_workflow_for_training[algo(PPOLag)] - FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use …
```
=> deps: pin pandas version

docs/source/saferl/lag.rst
It seems that the `$\lambda$` is missing after `value of`.
=> docs: add missing \lambda

omnisafe/common/experiment_grid.py
Modify the multi-process context to default `fork` to `spawn`.
close #314 
=> fix: fix cuda initialization error in experiment grid

omnisafe/adapter/online_adapter.py, omnisafe/envs/mujoco_env.py, omnisafe/envs/safety_gymnasium_env.py
OmniSafe and [Safety Gymnasium](https://github.com/PKU-Alignment/safety-gymnasium) both provide an `AutoReset` Wrapper, which automatically calls the reset function to refresh when the current episode ends. This PR is used to fix the issue of environment information getting mixed up due to the repeated use of auto reset.
=> fix: remove duplicated auto reset

.flake8, .pre-commit-config.yaml, conftest.py, omnisafe/algorithms/off_policy/ddpg.py, omnisafe/common/buffer/offpolicy_buffer.py, omnisafe/common/buffer/vector_offpolicy_buffer.py, omnisafe/configs/off-policy/SAC.yaml, omnisafe/configs/off-policy/SACLag.yaml, omnisafe/configs/on-policy/CPO.yaml, omnisafe/configs/on-policy/PPO.yaml, omnisafe/configs/on-policy/PPOLag.yaml, omnisafe/envs/__init__.py, omnisafe/envs/meta_drive_env.py, omnisafe/envs/safety_isaac_gym_env.py, omnisafe/evaluator.py, omnisafe/utils/config.py, pyproject.toml, tests/.coveragerc
**This PR is already complete in terms of implementation accuracy. We will merge it shortly after improving the code style and documentation.**
This PR supports `SafeMetaDrive` from [MetaDrive](https://github.com/metadriverse/metadrive)[1].
[1]: [Metadrive: Composing diverse driving scenarios for generalizable reinforcement learning](https://arxiv.org/pdf/2109.12674.pdf)
Autonomous driving is an important application of reinforcement learning algorithms, and safety is particularly crucial. Safety constraints for autonomous driving tasks are an important research direction in the SafeRL field. We have implemented the embedding of SafeMetaDrive based on our customized environment interface (more details in #310 ) and presented the SafeRL baseline algorithms involved in the MetaDrive paper …
=> feat: support metadrive env
